package br.com.netflics.core.security;

import br.com.netflics.model.User;
/**
*  generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21
**/

public interface UserContext {

	User getCurrentUser();

	String getCurrentUserName();
	
	void setCurrentUser(User user);
}
