package br.com.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
public class FilterMovieCast implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer order;  			
	private String characterName;  			

	private Integer movie;		
	private Integer gender;		
	private Integer person;		
	
	public  FilterMovieCast() {
		
	}

	public Integer getOrder() {
		return order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}
	public String getCharacterName() {
		return characterName;
	}

	public void setCharacterName(String characterName) {
		this.characterName = characterName;
	}
		
	public Integer getMovie() {
		return movie;
	}
	
	public void setMovie(Integer movie) {
		this.movie = movie;
	}
	public Integer getGender() {
		return gender;
	}
	
	public void setGender(Integer gender) {
		this.gender = gender;
	}
	public Integer getPerson() {
		return person;
	}
	
	public void setPerson(Integer person) {
		this.person = person;
	}
}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21