package br.com.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
public class FilterGenre implements Serializable {
	private static final long serialVersionUID = 1L;
	private String genreName;  			

	
	public  FilterGenre() {
		
	}

	public String getGenreName() {
		return genreName;
	}

	public void setGenreName(String genreName) {
		this.genreName = genreName;
	}
		
}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21