package br.com.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
public class FilterGender implements Serializable {
	private static final long serialVersionUID = 1L;
	private String gender;  			

	
	public  FilterGender() {
		
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}
		
}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21