package br.com.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
public class FilterCountry implements Serializable {
	private static final long serialVersionUID = 1L;
	private String name;  			
	private String isoCode;  			

	
	public  FilterCountry() {
		
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getIsoCode() {
		return isoCode;
	}

	public void setIsoCode(String isoCode) {
		this.isoCode = isoCode;
	}
		
}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21