package br.com.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
public class FilterMovieCrew implements Serializable {
	private static final long serialVersionUID = 1L;
	private String job;  			

	private Integer movie;		
	private Integer person;		
	private Integer department;		
	
	public  FilterMovieCrew() {
		
	}

	public String getJob() {
		return job;
	}

	public void setJob(String job) {
		this.job = job;
	}
		
	public Integer getMovie() {
		return movie;
	}
	
	public void setMovie(Integer movie) {
		this.movie = movie;
	}
	public Integer getPerson() {
		return person;
	}
	
	public void setPerson(Integer person) {
		this.person = person;
	}
	public Integer getDepartment() {
		return department;
	}
	
	public void setDepartment(Integer department) {
		this.department = department;
	}
}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21