package br.com.netflics.model.filter;

import java.io.Serializable;

import java.time.LocalDate;
import java.time.LocalDateTime;

/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
public class FilterDepartment implements Serializable {
	private static final long serialVersionUID = 1L;
	private String departmentName;  			

	
	public  FilterDepartment() {
		
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}
		
}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21