/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;

import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import br.com.netflics.core.model.Tenant ;

import br.com.netflics.model.Company;
import br.com.netflics.persistence.CompanyRepository;
import br.com.netflics.persistence.CompanySpecificationHelper;
import br.com.netflics.model.filter.FilterCompany;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.rs.exception.ValidationException;
import br.com.netflics.core.persistence.pagination.SearchParameters;
import br.com.netflics.core.utils.DateUtil;
import br.com.netflics.core.utils.Util;

@Service
@Transactional
public class CompanyServiceImp implements CompanyService {

	public static final Logger LOGGER = LoggerFactory.getLogger(CompanyServiceImp.class);
	
	@Autowired
	CompanyRepository companyRepository;
	
	public Optional<Company> get(Integer id, Tenant tenant) {
		return companyRepository.findOne(CompanySpecificationHelper.fromId(id, tenant));
	}

	public Pager<Company> get(SearchParameters<FilterCompany> searchParams, Tenant tenant) {
		Pageable pageRequest = searchParams.getPageRequest();

		Page<Company> page = companyRepository.findAll(CompanySpecificationHelper.filter(searchParams, tenant), pageRequest);

		return new Pager<Company>(page.getContent(), searchParams.getPage(), searchParams.getPageSize(),
		        searchParams.getOrder(), searchParams.getOrderBy(), page.getTotalElements());
	}

	public Boolean delete(Integer id, Tenant tenant) {
		Optional<Company> optional = this.get(id, tenant);
		if (optional.isPresent()) {
			companyRepository.delete(optional.get());
		}
		return true;
	}

	public Company save(Company entity) {
		return companyRepository.save(entity);
	}

	public Company update(Company entity) {
		return companyRepository.save(entity);
	}
}

//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21