/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Country;
import br.com.netflics.model.filter.FilterCountry;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface CountryService {

	
	public Optional<Country> get(Integer id, Tenant tenant) ;

	public Pager<Country> get(SearchParameters<FilterCountry> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Country save(Country entity) ;

	public Country update(Country entity) ;

}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21