/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;

import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import br.com.netflics.core.model.Tenant ;

import br.com.netflics.model.Country;
import br.com.netflics.persistence.CountryRepository;
import br.com.netflics.persistence.CountrySpecificationHelper;
import br.com.netflics.model.filter.FilterCountry;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.rs.exception.ValidationException;
import br.com.netflics.core.persistence.pagination.SearchParameters;
import br.com.netflics.core.utils.DateUtil;
import br.com.netflics.core.utils.Util;

@Service
@Transactional
public class CountryServiceImp implements CountryService {

	public static final Logger LOGGER = LoggerFactory.getLogger(CountryServiceImp.class);
	
	@Autowired
	CountryRepository countryRepository;
	
	public Optional<Country> get(Integer id, Tenant tenant) {
		return countryRepository.findOne(CountrySpecificationHelper.fromId(id, tenant));
	}

	public Pager<Country> get(SearchParameters<FilterCountry> searchParams, Tenant tenant) {
		Pageable pageRequest = searchParams.getPageRequest();

		Page<Country> page = countryRepository.findAll(CountrySpecificationHelper.filter(searchParams, tenant), pageRequest);

		return new Pager<Country>(page.getContent(), searchParams.getPage(), searchParams.getPageSize(),
		        searchParams.getOrder(), searchParams.getOrderBy(), page.getTotalElements());
	}

	public Boolean delete(Integer id, Tenant tenant) {
		Optional<Country> optional = this.get(id, tenant);
		if (optional.isPresent()) {
			countryRepository.delete(optional.get());
		}
		return true;
	}

	public Country save(Country entity) {
		return countryRepository.save(entity);
	}

	public Country update(Country entity) {
		return countryRepository.save(entity);
	}
}

//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21