/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;

import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import br.com.netflics.core.model.Tenant ;

import br.com.netflics.model.Department;
import br.com.netflics.persistence.DepartmentRepository;
import br.com.netflics.persistence.DepartmentSpecificationHelper;
import br.com.netflics.model.filter.FilterDepartment;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.rs.exception.ValidationException;
import br.com.netflics.core.persistence.pagination.SearchParameters;
import br.com.netflics.core.utils.DateUtil;
import br.com.netflics.core.utils.Util;

@Service
@Transactional
public class DepartmentServiceImp implements DepartmentService {

	public static final Logger LOGGER = LoggerFactory.getLogger(DepartmentServiceImp.class);
	
	@Autowired
	DepartmentRepository departmentRepository;
	
	public Optional<Department> get(Integer id, Tenant tenant) {
		return departmentRepository.findOne(DepartmentSpecificationHelper.fromId(id, tenant));
	}

	public Pager<Department> get(SearchParameters<FilterDepartment> searchParams, Tenant tenant) {
		Pageable pageRequest = searchParams.getPageRequest();

		Page<Department> page = departmentRepository.findAll(DepartmentSpecificationHelper.filter(searchParams, tenant), pageRequest);

		return new Pager<Department>(page.getContent(), searchParams.getPage(), searchParams.getPageSize(),
		        searchParams.getOrder(), searchParams.getOrderBy(), page.getTotalElements());
	}

	public Boolean delete(Integer id, Tenant tenant) {
		Optional<Department> optional = this.get(id, tenant);
		if (optional.isPresent()) {
			departmentRepository.delete(optional.get());
		}
		return true;
	}

	public Department save(Department entity) {
		return departmentRepository.save(entity);
	}

	public Department update(Department entity) {
		return departmentRepository.save(entity);
	}
}

//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21