/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Department;
import br.com.netflics.model.filter.FilterDepartment;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface DepartmentService {

	
	public Optional<Department> get(Integer id, Tenant tenant) ;

	public Pager<Department> get(SearchParameters<FilterDepartment> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Department save(Department entity) ;

	public Department update(Department entity) ;

}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21