/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Gender;
import br.com.netflics.model.filter.FilterGender;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface GenderService {

	
	public Optional<Gender> get(Integer id, Tenant tenant) ;

	public Pager<Gender> get(SearchParameters<FilterGender> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Gender save(Gender entity) ;

	public Gender update(Gender entity) ;

}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21