/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;

import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import br.com.netflics.core.model.Tenant ;

import br.com.netflics.model.Keyword;
import br.com.netflics.persistence.KeywordRepository;
import br.com.netflics.persistence.KeywordSpecificationHelper;
import br.com.netflics.model.filter.FilterKeyword;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.rs.exception.ValidationException;
import br.com.netflics.core.persistence.pagination.SearchParameters;
import br.com.netflics.core.utils.DateUtil;
import br.com.netflics.core.utils.Util;

@Service
@Transactional
public class KeywordServiceImp implements KeywordService {

	public static final Logger LOGGER = LoggerFactory.getLogger(KeywordServiceImp.class);
	
	@Autowired
	KeywordRepository keywordRepository;
	
	public Optional<Keyword> get(Integer id, Tenant tenant) {
		return keywordRepository.findOne(KeywordSpecificationHelper.fromId(id, tenant));
	}

	public Pager<Keyword> get(SearchParameters<FilterKeyword> searchParams, Tenant tenant) {
		Pageable pageRequest = searchParams.getPageRequest();

		Page<Keyword> page = keywordRepository.findAll(KeywordSpecificationHelper.filter(searchParams, tenant), pageRequest);

		return new Pager<Keyword>(page.getContent(), searchParams.getPage(), searchParams.getPageSize(),
		        searchParams.getOrder(), searchParams.getOrderBy(), page.getTotalElements());
	}

	public Boolean delete(Integer id, Tenant tenant) {
		Optional<Keyword> optional = this.get(id, tenant);
		if (optional.isPresent()) {
			keywordRepository.delete(optional.get());
		}
		return true;
	}

	public Keyword save(Keyword entity) {
		return keywordRepository.save(entity);
	}

	public Keyword update(Keyword entity) {
		return keywordRepository.save(entity);
	}
}

//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21