/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Keyword;
import br.com.netflics.model.filter.FilterKeyword;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface KeywordService {

	
	public Optional<Keyword> get(Integer id, Tenant tenant) ;

	public Pager<Keyword> get(SearchParameters<FilterKeyword> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Keyword save(Keyword entity) ;

	public Keyword update(Keyword entity) ;

}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21