/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Language;
import br.com.netflics.model.filter.FilterLanguage;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface LanguageService {

	
	public Optional<Language> get(Integer id, Tenant tenant) ;

	public Pager<Language> get(SearchParameters<FilterLanguage> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Language save(Language entity) ;

	public Language update(Language entity) ;

}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21