/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.MovieCast;
import br.com.netflics.model.filter.FilterMovieCast;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface MovieCastService {

	
	public Optional<MovieCast> get(Integer id, Tenant tenant) ;

	public Pager<MovieCast> get(SearchParameters<FilterMovieCast> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public MovieCast save(MovieCast entity) ;

	public MovieCast update(MovieCast entity) ;

}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21