/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;

import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import br.com.netflics.core.model.Tenant ;

import br.com.netflics.model.MovieCast;
import br.com.netflics.persistence.MovieCastRepository;
import br.com.netflics.persistence.MovieCastSpecificationHelper;
import br.com.netflics.model.filter.FilterMovieCast;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.rs.exception.ValidationException;
import br.com.netflics.core.persistence.pagination.SearchParameters;
import br.com.netflics.core.utils.DateUtil;
import br.com.netflics.core.utils.Util;

@Service
@Transactional
public class MovieCastServiceImp implements MovieCastService {

	public static final Logger LOGGER = LoggerFactory.getLogger(MovieCastServiceImp.class);
	
	@Autowired
	MovieCastRepository movieCastRepository;
	
	public Optional<MovieCast> get(Integer id, Tenant tenant) {
		return movieCastRepository.findOne(MovieCastSpecificationHelper.fromId(id, tenant));
	}

	public Pager<MovieCast> get(SearchParameters<FilterMovieCast> searchParams, Tenant tenant) {
		Pageable pageRequest = searchParams.getPageRequest();

		Page<MovieCast> page = movieCastRepository.findAll(MovieCastSpecificationHelper.filter(searchParams, tenant), pageRequest);

		return new Pager<MovieCast>(page.getContent(), searchParams.getPage(), searchParams.getPageSize(),
		        searchParams.getOrder(), searchParams.getOrderBy(), page.getTotalElements());
	}

	public Boolean delete(Integer id, Tenant tenant) {
		Optional<MovieCast> optional = this.get(id, tenant);
		if (optional.isPresent()) {
			movieCastRepository.delete(optional.get());
		}
		return true;
	}

	public MovieCast save(MovieCast entity) {
		return movieCastRepository.save(entity);
	}

	public MovieCast update(MovieCast entity) {
		return movieCastRepository.save(entity);
	}
}

//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21