/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.MovieCrew;
import br.com.netflics.model.filter.FilterMovieCrew;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface MovieCrewService {

	
	public Optional<MovieCrew> get(Integer id, Tenant tenant) ;

	public Pager<MovieCrew> get(SearchParameters<FilterMovieCrew> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public MovieCrew save(MovieCrew entity) ;

	public MovieCrew update(MovieCrew entity) ;

}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21