/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Person;
import br.com.netflics.model.filter.FilterPerson;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface PersonService {

	
	public Optional<Person> get(Integer id, Tenant tenant) ;

	public Pager<Person> get(SearchParameters<FilterPerson> searchParams, Tenant tenant) ;
	
	public Boolean delete(Integer id, Tenant tenant);

	public Person save(Person entity) ;

	public Person update(Person entity) ;

}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21