/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.service;
import java.util.Optional;

import java.util.List;
import java.time.LocalDateTime;
import java.time.LocalDate;
import br.com.netflics.core.model.Tenant;
import br.com.netflics.model.Role;
import br.com.netflics.model.filter.FilterRole;

import br.com.netflics.core.persistence.pagination.Pager;
import br.com.netflics.core.persistence.pagination.SearchParameters;

public interface RoleService {

	
	public Optional<Role> get(Integer id) ;

	public Pager<Role> get(SearchParameters<FilterRole> searchParams) ;
	
	public Boolean delete(Integer id);

	public Role save(Role entity) ;

	public Role update(Role entity) ;

}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21