package br.com.netflics.json;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import java.time.LocalDate;
import java.time.LocalDateTime;


/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
public class JsonMovieCrew implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String job;
	private JsonMovie movie;		
	private JsonPerson person;		
	private JsonDepartment department;		
	
	public  JsonMovieCrew() {
		
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getJob() {
		return job;
	}

	public void setJob(String job) {
		this.job = job;
	}
	
	public JsonMovie getMovie() {
		return movie;
	}
	
	public void setMovie(JsonMovie movie) {
		this.movie = movie;
	}
	public JsonPerson getPerson() {
		return person;
	}
	
	public void setPerson(JsonPerson person) {
		this.person = person;
	}
	public JsonDepartment getDepartment() {
		return department;
	}
	
	public void setDepartment(JsonDepartment department) {
		this.department = department;
	}

}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21