package br.com.netflics.json;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import java.time.LocalDate;
import java.time.LocalDateTime;


/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
public class JsonMovie implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String title;
	private Integer budget;
	private String homepage;
	private String overview;
	private String popularity;
	private LocalDate releaseDate;  			
	private String revenue;
	private Integer runtime;
	private String status;
	private String tagline;
	private String voteAverage;
	private Integer voteCount;
	private ArrayList<JsonLanguage> languages = new ArrayList<JsonLanguage>();	
	private ArrayList<JsonCountry> countries = new ArrayList<JsonCountry>();	
	private ArrayList<JsonKeyword> keywords = new ArrayList<JsonKeyword>();	
	private ArrayList<JsonMovieCrew> crew = new ArrayList<JsonMovieCrew>();		
	private ArrayList<JsonMovieCast> cast = new ArrayList<JsonMovieCast>();		
	private ArrayList<JsonGenre> genres = new ArrayList<JsonGenre>();	
	private ArrayList<JsonCompany> company = new ArrayList<JsonCompany>();	
	
	public  JsonMovie() {
		
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	public Integer getBudget() {
		return budget;
	}

	public void setBudget(Integer budget) {
		this.budget = budget;
	}
	public String getHomepage() {
		return homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}
	public String getOverview() {
		return overview;
	}

	public void setOverview(String overview) {
		this.overview = overview;
	}
	public String getPopularity() {
		return popularity;
	}

	public void setPopularity(String popularity) {
		this.popularity = popularity;
	}
	public LocalDate getReleaseDate() {
		return releaseDate;
	}

	public void setReleaseDate(LocalDate releaseDate) {
		this.releaseDate = releaseDate;
	}				
								
	public String getRevenue() {
		return revenue;
	}

	public void setRevenue(String revenue) {
		this.revenue = revenue;
	}
	public Integer getRuntime() {
		return runtime;
	}

	public void setRuntime(Integer runtime) {
		this.runtime = runtime;
	}
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	public String getTagline() {
		return tagline;
	}

	public void setTagline(String tagline) {
		this.tagline = tagline;
	}
	public String getVoteAverage() {
		return voteAverage;
	}

	public void setVoteAverage(String voteAverage) {
		this.voteAverage = voteAverage;
	}
	public Integer getVoteCount() {
		return voteCount;
	}

	public void setVoteCount(Integer voteCount) {
		this.voteCount = voteCount;
	}
	
	public ArrayList<JsonLanguage> getLanguages() {
		return languages;
	}
	
	public void setLanguages(ArrayList<JsonLanguage> language) {
		this.languages = language;
	}

	public ArrayList<JsonCountry> getCountries() {
		return countries;
	}
	
	public void setCountries(ArrayList<JsonCountry> country) {
		this.countries = country;
	}

	public ArrayList<JsonKeyword> getKeywords() {
		return keywords;
	}
	
	public void setKeywords(ArrayList<JsonKeyword> keyword) {
		this.keywords = keyword;
	}

	public ArrayList<JsonMovieCrew> getCrew() {
		return crew;
	}
	
	public void setCrew(ArrayList<JsonMovieCrew> movieCrew) {
		this.crew = movieCrew;
	}

	public ArrayList<JsonMovieCast> getCast() {
		return cast;
	}
	
	public void setCast(ArrayList<JsonMovieCast> movieCast) {
		this.cast = movieCast;
	}

	public ArrayList<JsonGenre> getGenres() {
		return genres;
	}
	
	public void setGenres(ArrayList<JsonGenre> genre) {
		this.genres = genre;
	}

	public ArrayList<JsonCompany> getCompany() {
		return company;
	}
	
	public void setCompany(ArrayList<JsonCompany> company) {
		this.company = company;
	}


}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21