package br.com.netflics.json;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import java.time.LocalDate;
import java.time.LocalDateTime;


/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
public class JsonMovieCast implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer order;
	private String characterName;
	private JsonMovie movie;		
	private JsonGender gender;		
	private JsonPerson person;		
	
	public  JsonMovieCast() {
		
	}
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getOrder() {
		return order;
	}

	public void setOrder(Integer order) {
		this.order = order;
	}
	public String getCharacterName() {
		return characterName;
	}

	public void setCharacterName(String characterName) {
		this.characterName = characterName;
	}
	
	public JsonMovie getMovie() {
		return movie;
	}
	
	public void setMovie(JsonMovie movie) {
		this.movie = movie;
	}
	public JsonGender getGender() {
		return gender;
	}
	
	public void setGender(JsonGender gender) {
		this.gender = gender;
	}
	public JsonPerson getPerson() {
		return person;
	}
	
	public void setPerson(JsonPerson person) {
		this.person = person;
	}

}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21