/* generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21 */
package br.com.netflics.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;

import java.time.LocalDate;
import java.time.LocalDateTime;
	
import java.util.ArrayList;
import java.util.List;

import br.com.netflics.core.model.AbstractMultitenantEntity;

@Entity
@Table(name = "KEYWORD")
public class Keyword extends AbstractMultitenantEntity{
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)	
	private Integer id;
	
	@Column(name = "KEYWORD_NAME" )
	private String name;		
	
    @ManyToMany(mappedBy="keywords")
    private List<Movie> movies;
		
	public  Keyword() {
		
	}
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public void setMovies(List<Movie> movies){
		this.movies = movies;
	}
	
	public List<Movie>  getMovies() {
		if(this.movies == null){
			setMovies(new ArrayList<Movie>());
		}
		return this.movies; 
	}
		
	public boolean addMovies(Movie movie){	
		return getMovies().add(movie);
	}
	
	public boolean removeMovies(Movie movie){	
		return getMovies().remove(movie);
	}
	
}
//generated by JSetup v0.95 :  at 1 de fev de 2023 23:43:21